const {_electron:electron}=require("playwright");
const fs=require("node:fs"),os=require("node:os"),path=require("node:path"),assert=require("node:assert/strict");
const output = process.env.CIKE_ARTIFACT_DIR || "artifacts";
fs.mkdirSync(output,{recursive:true});
(async()=>{
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"cike-companion-"));
let app;
try {
app=await electron.launch({...(process.env.CIKE_EXECUTABLE?{executablePath:process.env.CIKE_EXECUTABLE,args:[]}:{args:[path.resolve(__dirname,"..")]}),env:{...process.env,CIKE_TEST_DIR:dir}});
await app.evaluate(({powerMonitor})=>powerMonitor.getSystemIdleTime=()=>600);
const p=await app.firstWindow(), errors=[];
p.on("pageerror",e=>errors.push(e.message));
await p.waitForSelector("#pet.scene");
await p.emulateMedia({reducedMotion:"no-preference"});
assert.equal(await p.locator("#high-five").isVisible(),false);
await p.evaluate(()=>window.cike.call("request"));
await p.waitForSelector("#bubble.visible");
await p.locator("#complete").click();
await p.waitForFunction(()=>document.querySelector("#high-five").dataset.phase==="ready");
await p.waitForTimeout(200);
await p.screenshot({path:path.join(output,"0.6.1-举手击掌.png")});
await p.locator("#high-five").click();
await p.waitForFunction(()=>document.querySelector("#high-five").dataset.phase==="done");
assert.equal(await p.locator("#high-five").isVisible(),false);
await p.waitForTimeout(200);
await p.screenshot({path:path.join(output,"0.6.1-击掌完成.png")});
await p.waitForFunction(()=>document.querySelector("#high-five").dataset.phase==="");
assert.equal(await p.locator("#high-five").isVisible(),false);
await p.evaluate(()=>idleTick());
await p.waitForTimeout(250);
const a=await p.locator("#creature").getAttribute("src");
await p.screenshot({path:path.join(output,"0.6.1-安静表情.png")});
await p.evaluate(()=>idleTick());
await p.waitForTimeout(250);
assert.notEqual(a,await p.locator("#creature").getAttribute("src"));
await p.emulateMedia({reducedMotion:"reduce"});
const step=await p.evaluate(()=>idleStep);
await p.evaluate(()=>idleTick());
assert.equal(step,await p.evaluate(()=>idleStep));
await p.evaluate(()=>window.cike.call("preview","12:00"));
await p.waitForFunction(()=>document.querySelector("#bubble-label").textContent.startsWith("时段预览"));
await p.locator("#dismiss").click();
await p.evaluate(()=>window.cike.call("request"));
await p.waitForFunction(()=>!document.querySelector("#bubble-label").textContent.includes("时段预览"));
await p.evaluate(async()=>{activeItem.moment.scene="obsolete";await refreshMoment();});
assert.equal(await p.locator("#bubble").getAttribute("class"),"");
await p.evaluate(()=>window.cike.call("request"));
await p.locator("#complete").click();
await p.waitForFunction(()=>document.querySelector("#high-five").dataset.phase==="ready");
await p.waitForFunction(()=>document.querySelector("#high-five").dataset.phase==="",{},{timeout:18000});
assert.equal(await p.locator("#high-five").isVisible(),false);
assert.deepEqual(errors,[]);
console.log("PASS: 举手/击掌/收回、安静变化、减少动画、预览隔离、过时卡收起、无页面错误");
} finally {if(app)await app.close();fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
