const {_electron:electron}=require('playwright'),fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/0.8.0');fs.mkdirSync(out,{recursive:true});
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cike-080-'));let app;const errors=[];const launch=()=>electron.launch({executablePath:path.join(root,'dist/0.8.0/mac-arm64/此刻.app/Contents/MacOS/此刻'),args:[],env:{...process.env,CIKE_TEST_DIR:dir,CIKE_VOICE_RUNTIME:path.join(dir,'no-engine')}});try{
app=await launch();let pet=await app.firstWindow();await pet.waitForSelector('#pet');pet.on('pageerror',e=>errors.push(e.message));await pet.evaluate(()=>cike.call('customizer'));let hub;for(let i=0;i<50;i++){hub=app.windows().find(w=>w.url().endsWith('customize.html'));if(hub)break;await new Promise(r=>setTimeout(r,100));}
if(!hub)hub=app.windows().find(w=>w.url().endsWith('customize.html'));await hub.waitForFunction(()=>document.querySelector('#count').textContent.includes('136'));hub.on('pageerror',e=>errors.push(e.message));
assert.equal((await pet.evaluate(()=>cike.call('get'))).appVersion,'0.8.0');await hub.screenshot({path:path.join(out,'定制概览.png')});
await app.evaluate(({Menu})=>{const original=Menu.buildFromTemplate;Menu.buildFromTemplate=function(rows){global.testMenu=rows;return original.call(this,rows)};Menu.prototype.popup=function(){};});await pet.evaluate(()=>cike.call('menu'));const labels=await app.evaluate(()=>global.testMenu.filter(r=>r.label).map(r=>r.label));assert.deepEqual(labels,['给我一个小动作','暂停自动提醒','播放声音','设置与定制…','回到屏幕角落','退出此刻']);fs.writeFileSync(path.join(out,'菜单核验.json'),JSON.stringify(labels,null,2));
await app.evaluate(()=>global.testMenu.find(r=>r.label==='暂停自动提醒').click());assert.equal((await pet.evaluate(()=>cike.call('get'))).settings.enabled,false);await app.evaluate(()=>global.testMenu.find(r=>r.label==='暂停自动提醒').click());
await hub.locator('[data-tab="actions"]').click();await hub.locator('#new-action').click();await hub.locator('#title').fill('给绿植一点水');await hub.locator('#text').fill('看看手边的绿植，土干了就浇一点水。');await hub.locator('#scene').selectOption('afternoon');await hub.locator('#closing').fill('浇一点就好，陪它慢慢长。');await hub.locator('#editor button[type="submit"]').click();await hub.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('已保存'));const custom=(await pet.evaluate(()=>cike.call('get'))).custom[0];assert.equal(custom.scenes[0],'afternoon');
await hub.locator('#preview-action').click();await pet.locator('#bubble.visible').waitFor();assert.equal(await pet.locator('#bubble-title').textContent(),'给绿植一点水');await hub.locator('#editor').screenshot({path:path.join(out,'小动作编辑.png')});await pet.screenshot({path:path.join(out,'自定义小动作桌面.png')});
await hub.locator('#voice-action').click();let voice;for(let i=0;i<50;i++){voice=app.windows().find(w=>w.url().endsWith('voice.html'));if(voice)break;await new Promise(r=>setTimeout(r,100));}await voice.waitForFunction(()=>document.querySelector('#line-text').textContent==='看看手边的绿植，土干了就浇一点水。');assert.match(await voice.locator('#engine-status').textContent(),/尚未准备/);await voice.close();
// Test native file selection using a local non-square fixture; image processing remains real.
const fixture=path.join(dir,'wide.png');const png=await app.evaluate(({nativeImage},p)=>nativeImage.createFromPath(p).resize({width:400,height:200}).toPNG().toString('base64'),path.join(root,'assets/icon.png'));fs.writeFileSync(fixture,Buffer.from(png,'base64'));
await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]});},fixture);
await hub.locator('#pick-action-image').click();await hub.waitForFunction(()=>document.querySelector('#action-image').src.startsWith('data:image/png'));await hub.locator('#preview-action').click();await pet.waitForFunction(()=>document.querySelector('#creature').src.startsWith('data:image/png'));await hub.locator('#row-enabled').uncheck();await hub.locator('#editor button[type="submit"]').click();await hub.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('已保存'));assert.ok((await pet.evaluate(()=>cike.call('get'))).memory.blocked.includes(custom.id));
await hub.locator('[data-tab="look"]').click();await hub.locator('#pick-image').click();await hub.waitForFunction(()=>!document.querySelector('#apply-image').disabled);assert.equal((await pet.evaluate(()=>cike.call('get'))).image,null);await hub.locator('#apply-image').click();await hub.waitForFunction(()=>document.querySelector('#apply-image').disabled);const image=(await pet.evaluate(()=>cike.call('get'))).image;assert.ok(image.startsWith('data:image/png'));const size=await app.evaluate(({nativeImage},image)=>nativeImage.createFromDataURL(image).getSize(),image);assert.equal(size.width/size.height,2);await hub.screenshot({path:path.join(out,'形象配置.png')});
await hub.locator('#restore-image').click();await hub.waitForFunction(()=>document.querySelector('#status').textContent.includes('已使用小纸团'));assert.equal((await pet.evaluate(()=>cike.call('get'))).image,null);
// Backup import validation and successful replacement, preserving a pre-restore copy.
const backup=path.join(dir,'backup.json'),saved=await pet.evaluate(()=>cike.call('get'));fs.writeFileSync(backup,JSON.stringify(saved));await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]});dialog.showMessageBox=async()=>({response:1});},backup);await hub.locator('[data-tab="data"]').click();await hub.locator('#restore-data').click();await hub.waitForFunction(()=>document.querySelector('#status').textContent.includes('配置已导入'));assert.ok(fs.existsSync(path.join(dir,'companion.before-restore.json')));
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle().includes('设置与定制')).setSize(760,740));await hub.locator('[data-tab="actions"]').click();await hub.waitForFunction(()=>innerWidth===760);assert.ok(await hub.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await hub.screenshot({path:path.join(out,'小动作窄窗口.png'),fullPage:true});
await app.close();app=await launch();pet=await app.firstWindow();await pet.waitForSelector('#pet');const restored=await pet.evaluate(()=>cike.call('get'));assert.equal(restored.custom[0].text,custom.text);assert.ok(restored.custom[0].image);assert.ok(restored.memory.blocked.includes(custom.id));assert.deepEqual(errors,[]);console.log('PASS 0.8.0 final package: clean offline/no engine, six menu actions, create/edit/scene/preview/voice selection, image preview and aspect ratio, disable, restart, backup restore, narrow layout, screenshots.');
}finally{if(app)await app.close();fs.rmSync(dir,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
